
# Subject: You also have to write your own Dockerfiles, one per service. The Dockerfiles must be called in your docker-compose.yml by your Makefile.

version: '3'

services:
  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always


  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: always


  mariadb:
    build:
      context: ./requirements/mariadb
    container_name: mariadb
    restart: always

volumes:
  wordpress-db:
  wordpress-files:
